version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: accounts-postgres
    environment:
      POSTGRES_DB: accounts_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: accounts-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_PORT: 8080
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: postgres
      DB_SSLMODE: disable
      LOG_LEVEL: info
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data: